# --- Required options --- #

# Name of website
title: Bits in Flight

# Your name to show in the footer
author: Mike Williams

# --- Remote theme --- #
remote_theme: daattali/beautiful-jekyll@master

# --- List of links in the navigation bar --- #
navbar-links:
  Home: "/"
  About: "about"
  Categories:
    - Piaware: "category/piaware"
    - .NET: "category/dotnet"

# --- Logo --- #
# avatar: "/assets/img/avatar-icon.png"
round-avatar: true

# --- Footer social media links --- #
social-network-links:
  email: "mike.williams@example.com"
  rss: true
  github: cmwilliams
#  twitter: yourusername
#  linkedin: yourusername

# --- Comments --- #
utterances:
  repo: cmwilliams/cmwilliams.github.io
  issue-term: pathname

# --- General options --- #
url: "https://mikewilliams.io"
baseurl: ""

# RSS feed description
rss-description: A blog about technology, programming, and tutorials on Piaware and .NET.

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# How to display the link to your website in the footer
url-pretty: "mikewilliams.io"

# Add the website title to the title of every page
title-on-all-pages: true

# Excerpt word length
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

# --- Colours / background image --- #
navbar-col: "#FFFFFF"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# --- Output options --- #
timezone: "America/New_York"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  - scope:
      path: ""
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme
